### ISSUE TITLE
20 lines of code

### ISSUE THREAD

**Issue by cannyboy** [mamaral/Neon#1]
>  In the meantime, here's an intentionally convoluted example to show how easy it is to build very complex and dynamic layouts with Neon. The following layout was created with only 20 lines of code. 

Can we see this code? Thanks.

**Comment by mamaral** [comment]
Check out the demo project. It's in one of the three view controllers there.

**Comment by cannyboy** [comment]
Great thanks. In that example, is there a way to adjust the shapes via the dark grey lines? Like the gif in this prototype?

https://github.com/MrNickBarker/iOSAccordionPanels

**Comment by mamaral** [comment]
I'm sure it could be done, but that would be related to how you handled user interaction. In my example I just used a single anchor view that follows user touch events. You'd have to write your own version that did what you wanted there but the layout stuff should just work.

**Comment by mamaral** [comment]
Let me know if you have any more questions!
