### ISSUE TITLE
Dynamic UIlabel

### ISSUE THREAD

**Issue by wieseljonas** [mamaral/Neon#12]
It's not a issue just a suggestion. at the moment I have UILabels that can have 1 to 2 lines depending and text size. 

at the moment I do this like this but I'm sure there is a better way

    let nameLabelHeight = nameLabel.text?.heightWithConstrainedWidth(self.width - 24 - profilePictureImageView.width, font: nameLabel.font)
        if let n = nameLabelHeight where n > 60 {
            nameLabel.alignAndFillWidth(align: .ToTheRightMatchingTop, relativeTo: profilePictureImageView, padding: 8, height: 60)
        } else if let n = nameLabelHeight {
            nameLabel.alignAndFillWidth(align: .ToTheRightMatchingTop, relativeTo: profilePictureImageView, padding: 8, height: n)
        }

**Comment by mamaral** [comment]
That is the #1 thing I plan to add and have a pretty good idea how I would handle it. Ultimately what I envision is you'll do something like this:

```
nameLabel.alignAndFillWidth(align: .ToTheRightMatchingTop, relativeTo: profilePictureImageView, padding: 8, height: LabelAutoHeight)
```

Under the covers that will *essentially* do the following (which is what I currently do myself)

```
nameLabel.alignAndFillWidth(align: .ToTheRightMatchingTop, relativeTo: profilePictureImageView, padding: 8, height: 0)
nameLabel.sizeToFit()
nameLabel.alignAndFillWidth(align: .ToTheRightMatchingTop, relativeTo: profilePictureImageView, padding: 8, height: nameLabel.height)
```

The reason you need to do something like that, it seems to me, is that the first pass through alignAndFillWidth() sets the width, and then when you sizeToFit() it uses that same width but dynamically sets the height based on that width, and then adjusts the `y` value so that it matches the intended alignment specified. Does that make sense?

**Comment by wieseljonas** [comment]
@mamaral  Thanks for the quick reply I will give it a spin and get back to you

**Comment by mamaral** [comment]
In case it wasn't clear, that first chunk of code with `LabelAutoHeight` has not been implemented yet, but in the meantime using those three lines with the sizeToFit() in the middle should auto-size and align the label correctly with any number of lines.

**Comment by wieseljonas** [comment]
@mamaral Ok got it. Thanks for the great work

**Comment by mamaral** [comment]
Implemented the first crack at it. Check this out and let me know if this is what you were thinking:

https://github.com/mamaral/Neon#what-about-labels

**Comment by mamaral** [comment]
You should be good to go, let me know if you have issues.

**Comment by wieseljonas** [comment]
I will give it a spin. If I can give a quick feedback. In my case a need to make sure the UILabel doesn't exceed a certain height. I think a maxHeight or maxWidth option could really be useful.

**Comment by wieseljonas** [comment]
Another 2 cents worth. In my case I'm not between 2 views but I need the label to fill the width from a view and the border of the superview. Maybe I didn't get fully and it's already possible.

**Comment by mamaral** [comment]
I don't have the max/min height capability, but you're able to pass in `AutoHeight` to any method that accepts a `height` param and the label will auto size and align appropriately.
