### ISSUE TITLE
Can't use for Objective-C Application

### ISSUE THREAD

**Issue by zixun** [mamaral/Neon#15]
Can't use for Objective-C Application.

I have import the Neon-swift.h file

**Comment by zdenektopic** [comment]
did u try @import Neon; instead of #import <Neon/Neon-swift.h>?

**Comment by zixun** [comment]
yes,i tried. the selector in Neon.swift can use,but in other file can't

**Comment by zixun** [comment]
make any process？

**Comment by richardoti** [comment]
I'm using Neon in  Objective-C Application right now.
The Neon framework is used in one UI-component, which is written in Swift. However, the rest of the app is Objective-C based.

**Comment by zixun** [comment]
how did you use with Neon? by CocoaPods?

**Comment by richardoti** [comment]
I've just copied the whole framework to the project.

**Comment by HTAD** [comment]
Use 'Facade'

**Comment by mamaral** [comment]
Let me know if you're still having issues, closing this for now.
