### ISSUE TITLE
error while carthage update

### ISSUE THREAD

**Issue by zixun** [mamaral/Neon#17]
I add the neon to my  Cartfile,but while Im  run  carthage update commond，terminal show an error:

      *** Fetching Neon
      *** Checking out Neon at "v0.0.2"
      *** xcodebuild output can be found in /var/folders/5y/x8t9wb3d1t33b77ckz509p_w0000gn/T/carthage-xcodebuild.JEhAhQ.log
     A shell task failed with exit code 66:
     xcodebuild: error: Scheme NeonMacDemo is not currently configured for the build action.

**Comment by schickling** [comment]
+1

**Comment by mamaral** [comment]
I didn't set up the carthage stuff, but I believe this has to do with setting the test target's scheme to shared for unit test coverage purposes. I'll look into this as soon as I can, although I've been quite busy with my 9-5 so can't promise it'll be very soon.

**Comment by zixun** [comment]
@mamaral  waiting for you~ by the way, I found the reason of the error: 

[error while carthage update](https://github.com/Carthage/Carthage/issues/896#issuecomment-155102100)

**Comment by ikesyo** [comment]
> I didn't set up the carthage stuff, but I believe this has to do with setting the test target's scheme to shared for unit test coverage purposes.

Sharing a scheme for non-framework target is valid. `Neon Demo` and `NeonUnitTests` schemes are also shared, but they don't have any problems.

In this case, the project does not have the target `NeonMacDemo` which is described in the `NeonMacDemo` scheme. You should delete the scheme since that is just a garbage and unnecessary.

**Comment by mamaral** [comment]
Should be addressed with #18. LMK if you still have issues.

**Comment by schickling** [comment]
Awesome. Thanks! :)
