### ISSUE TITLE
My Application is open source which used Neon for UI layout

### ISSUE THREAD

**Issue by zixun** [mamaral/Neon#22]
My Application( [CocoaChina+](https://github.com/zixun/CocoaChinaPlus) ) is open source. It used Neon for layout my UI.
and some of other swift opensource library,such as : [RxSwift](https://github.com/ReactiveX/RxSwift), [Ji](https://github.com/honghaoz/Ji)

Thanks for Neon 😄

**Comment by mamaral** [comment]
Glad you like it, thanks!
