### ISSUE TITLE
Offset layout question

### ISSUE THREAD

**Issue by RayTao** [mamaral/Neon#26]
![reloation](https://cloud.githubusercontent.com/assets/8056228/11611487/812c896c-9c0b-11e5-9a0a-5093c705b10c.png)
 How an I layout like the image? I think need xPad and yPad

**Comment by mamaral** [comment]
As of v0.2.0, which I just pushed, you now should be able to specify an `offset` param for all of the align methods. Let me know if that achieves what you're looking for!

**Comment by mitch10e** [comment]
I am unable to access the new code easily as the podspec file has not been updated to v0.2.0.

**Comment by mamaral** [comment]
@mitch10e I'll try and get that pushed ASAP.

**Comment by mamaral** [comment]
@mitch10e Try it now!
