### ISSUE TITLE
UILabel width

### ISSUE THREAD

**Issue by tim12s** [mamaral/Neon#31]
Hi,

Great work on making a super flexible and simple layout framework.

Any chance you can have tried to have UIButton and UILabel to automatically calculate their widths as per below where the width of a button/label can be calculated from its contents?

> button1.anchorInCorner**AndUseWidth**(.BottomLeft, xPad: 20, yPad: 20, height: 30)
> label2.align**AndUseWidth**(align: .ToTheRightMatchingTop, relativeTo: button1, padding: 20, height: 30)
> button3.alignAnd**Fill**Width(align: .ToTheRightMatchingTop, relativeTo: label2, padding: 20, height: 30)

Thanks for the elegant work,
-Tim

**Comment by tim12s** [comment]
It seems extending the framework and copying the AutoHeight concept to AutoWidth does the trick.  I'll submit a pull request.

**Comment by mamaral** [comment]
Excellent, thank you!

**Comment by tim12s** [comment]
Submitted #32 for review

**Comment by mamaral** [comment]
Thanks again!
