### ISSUE TITLE
Question: How is animation with neon?

### ISSUE THREAD

**Issue by Joker666** [mamaral/Neon#35]
I just saw the library, didn't dig into it much, but hopefully considering to use it. Just one concern, how is the basic animations with neon, what are the animation properties? Like with autolayout you animate the constraints constants which is a **pain** in the ass rather than normal uiview animations.

If the animation is breeze I'm all on with this layout system :)
👍

**Comment by mamaral** [comment]
Each of the functions are simply setting the frame, so I'm assuming you can simply wrap the method calls in your normal animation blocks and the changes should animate fine.

**Comment by Joker666** [comment]
Thanks :) Will try out for sure!
