### ISSUE TITLE
How to  autoheight UITableViewCell?

### ISSUE THREAD

**Issue by Orangerc** [mamaral/Neon#38]
When i use Neon，I can't use this gramera to autoHeight UITableViewCell
        self.tableView.rowHeight = UITableViewAutomaticDimension
        self.tableView.estimatedRowHeight = 300

Could you fix the problem?
Thank you.

**Comment by mamaral** [comment]
Unfortunately, Neon isn't built to handle that type of thing, it's a totally different mechanism.

**Comment by Orangerc** [comment]
This means,I can not use Neon in UITableViewCell?
Thank You.

**Comment by mamaral** [comment]
You can use neon to layout the views inside a cell, but you need to calculate the height of the cell yourself.

**Comment by Orangerc** [comment]
Thank You，I know.

**Comment by floler** [comment]
@Orangerc @mamaral is the a sample code snippet for creating TableViewCell with Neon? I am really struggeling with doing that :-/

**Comment by mamaral** [comment]
What are you struggling with exactly?

**Comment by floler** [comment]
I do set the height of the TV in the delegate methods in the viewcontroller. The cell does match the height but I really dont know how to perform something like the "layoutFrames()" function within the tableviewcell .. this is why I am looking for a sample codesnippet for a tableviewcell created with neon :-)

**Comment by mamaral** [comment]
Set frames in layoutSubviews

**Comment by floler** [comment]
Works perfect, thank you very much!

**Comment by mamaral** [comment]
Glad to help!
