### ISSUE TITLE
Update to Swift 3

### ISSUE THREAD

**Issue by mathmatrix828** [mamaral/Neon#39]
Already noticed a lot of updates are required. I may try to update some of the stuff, but I'm really busy at the moment. What are the plans to update Neon to Swift v3?

**Comment by mamaral** [comment]
Haven't taken a deep look into Swift 3 yet, but will try to get on this as soon as possible. In the meantime, if anyone wants to submit a PR that would be fantastic.

**Comment by mamaral** [comment]
Hoping to dive into this this weekend - will keep you updated.

**Comment by mathmatrix828** [comment]
Awesome

**Comment by mathmatrix828** [comment]
Any updates?

**Comment by mamaral** [comment]
I recently started a new job, and that coupled with other projects is eating up all my free time, so I haven't begun to even look into the docs, download the newest Xcode, etc., so this likely won't get done in the very near future unless someone submits a pull request.

**Comment by mathmatrix828** [comment]
Sounds good. I'm in the same position as far as free time, and I'm trying to update all of my current projects w/ to be compatible. I may try to put some time and submit a PR but it may not be likely. Thanks for your work!

**Comment by mamaral** [comment]
Looks like I may have it done actually... Was a bit easier than expected.. Let me test it out and get a new version up.

**Comment by mamaral** [comment]
Handled in https://github.com/mamaral/Neon/pull/45. I will update the CocoaPod version as soon as tests pass. I didn't go through and convert all the unit tests as that is pretty freaking arduous, but I'll get around to it eventually.

Updating every single line from `XCTAssert(CGRectEqualsToRect(testSiblingView.frame, CGRectMake(70, 10, 920, 40)))` to `XCTAssert(testAnchorView.frame == CGRect(x: 485, y: 10, width: 30, height: 40))` is pretty annoying work for a weeknight... :)

**Comment by mamaral** [comment]
Looks like xcodebuild is failing with swift 3 for some reason, meaning my pod wont pass lint, meaning I cant push to cocoapods yet...

**Comment by mathmatrix828** [comment]
Really? I'm using several pods in many of my projects and haven't had any issues with them, providing their syntax is correct

**Comment by mamaral** [comment]
My project builds fine but xcodebuild fails.

**Comment by mathmatrix828** [comment]
Odd. Maybe update CoacoPods?

**Comment by mamaral** [comment]
It's not CocoaPods, its the xcodebuild command itself.

**Comment by brcolow** [comment]
Is this supposed to be working at the moment? Using XCode 8 Beta 6, with the following line in my Podfile:

```
pod "Neon", :git => 'https://github.com/mamaral/neon.git', :tag => "v0.3.2"
```

Leads to this error:

```
/Users/brcolow/code/ios/Authenticator/Authenticator/TimeWheelViewController.swift:10:8: Module file was created by an older version of the compiler; rebuild 'Neon' and try again: /Users/brcolow/Library/Developer/Xcode/DerivedData/Authenticator-gigborldeqdjcgfcpytvmiksmpzi/Build/Products/Debug-iphoneos/Neon.framework/Modules/Neon.swiftmodule/arm64.swiftmodule
```

**Comment by mamaral** [comment]
I have not been able to push the update to CocoaPods, as far as I understand it'll have to wait until Xcode 8 is released.

**Comment by mathmatrix828** [comment]
I'd like to start looking into this, but I don't know enough about CP to really be able to help

**Comment by mamaral** [comment]
They have a pull request sitting there but won't merge until xcode 8 is released. AFAIK nothing for us to do but wait.

**Comment by mamaral** [comment]
I'm hoping https://github.com/CocoaPods/Xcodeproj/pull/407 will address this.

**Comment by brcolow** [comment]
Is it possible to use the master branch version of CP to address this, now that it is merged?

**Comment by mamaral** [comment]
On my way home from work. I'll look tonight.

**Comment by mathmatrix828** [comment]
Any updates? GM has been released and a lot of projects look good and work well with CP as of XC8

**Comment by mamaral** [comment]
PR being worked on as we speak. Once I get those changes merged and can get
the latest cocoa pods going I'll hopefully get it out soon.

**Comment by mathmatrix828** [comment]
Awesome stuff! Let me know if I can help!

**Comment by JFKingsley** [comment]
+1! Looking forward to it

**Comment by mamaral** [comment]
This has actually been a giant pain in my ass. For some reason running `pod lib lint` changed my remote repo URL to cocoapods instead of this repo, so that was fun figuring out... Now I need to determine if I can somehow set the swift version in my podspec, because I'm still not able to lint my podspec locally.

**Comment by mamaral** [comment]
Holy hell in a handbasket I think I got it... Try out pod version 0.3.4.3.

**Comment by mathmatrix828** [comment]
Awesome! I'll check it out tonight

**Comment by yuyongmao** [comment]
I didn't find  version 0.3.4.3, just found version 2.0

**Comment by mamaral** [comment]
What do you mean you "found" that version? Searching cocoapods for it shows the latest version. Did you run `pod update`?  https://cocoapods.org/?q=neon

**Comment by yuyongmao** [comment]
Awesome! I have checked it out , thank you very much!

**Comment by threat70** [comment]
Hello. Why you set min deployment ios version to 9.0? revert please to 8.0 if you can.
I have some projects with 8.0 support and i got upset when discovered this changes.

**Comment by mathmatrix828** [comment]
Some of the updates may not be compatible with iOS 8. 8 is currently in legacy and should not be supported

**Comment by mamaral** [comment]
@threat70 Just use a version that supports 8.

**Comment by threat70** [comment]
@mamaral but I want to use swift 3.0 :) Thanks for explanations.

**Comment by mamaral** [comment]
@threat70 Done.
