### ISSUE TITLE
Use Legacy Swift Language Version

### ISSUE THREAD

**Issue by rjalkuino** [mamaral/Neon#47]
I getting issue like this using carthage 

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by mamaral** [comment]
I'll take a look either tonight or this weekend. Thanks!

**Comment by mamaral** [comment]
Recent changes may have made this moot - let me know if you're still having issues.

**Comment by rjalkuino** [comment]
Thank you very much! I will try that next week.
