### ISSUE TITLE
Can't use cocoapods because the extension UIView is empty?

### ISSUE THREAD

**Issue by DJBen** [mamaral/Neon#5]
I tried integrating it with cocoapod. It can be imported correctly but I can't find any functions extended in UIView because that section is not public?

**Comment by mamaral** [comment]
I haven't pushed it to cocoapods yet. It's not exactly 100% production ready just yet. I'm adding more unit tests, doing more testing, and maybe a bit of refactoring, then I will get out the first version into cocoapods.

**Comment by mamaral** [comment]
I'd give it a try now that it's been pushed to CocoaPods. Let me know if you have issues!
