### ISSUE TITLE
Propose grouping without explicit size

### ISSUE THREAD

**Issue by richardtop** [mamaral/Neon#51]
Hello, 
I would like to propose idea of grouping without calculating the size of the group explicitly. In that case, Neon should call `sizeToFit` on each of the subviews and calculate the total size.
In addition to 

``` Swift
anchorViewA.groupInCenter(group: .Horizontal, views: [view1, view2, view3], padding: padding, width: size, height: size)
```

there would be this option

``` Swift
anchorViewA.groupInCenter(group: .Horizontal, views: [view1, view2, view3], padding: padding)
```

How do you feel about it?

The reason behind this feature is to group multiple items that are of different size.

**Comment by JanNash** [comment]
I'd love that. Maybe we should go about n implement it?
