### ISSUE TITLE
keep aspect-ratio of view

### ISSUE THREAD

**Issue by cyrus86** [mamaral/Neon#52]
I might just not see it, but is there any way to implement a dynamically sized view that keeps its aspect-ratio?  

Best Regards

**Comment by mamaral** [comment]
I don't see why not - can you give an example? You provide the width and height of the view in many cases, so if you do your own calculations with that aspect-ratio and feed in the correct sizes, it should just work.

**Comment by wdcurry** [comment]
This would truly round out this amazing repo. Group fill where each element of the filling array is assigned the required ratio rather than the currently set equality. THIS would be put to use immediately.
