### ISSUE TITLE
Button click action is not working

### ISSUE THREAD

**Issue by ebubekirguler** [mamaral/Neon#54]
Hi,
In TwitterProfileExampleViewController, i add a click event to cameraButton which is an UIButton, but the click action is not working. Can you help me please. thanks

`        cameraButton.setImage(UIImage(named: "camera"), for: .normal)
        cameraButton.addTarget(self, action: #selector(buttonAction), for: .touchUpInside)

    func buttonAction(sender: UIButton!) {
        var btnsendtag: UIButton = sender
        if btnsendtag.tag == 1 {
            //do anything here
        }
    }
`

**Comment by mamaral** [comment]
Do you need to add a colon to the selector code because your function takes a param? Been a bit since I wrote that in swift and I'm away from a computer at the moment. 

`#selector(buttonAction:)`

**Comment by mamaral** [comment]
I'm closing this now as this is very unlikely related to Neon, but can help if you need further help.
