### ISSUE TITLE
iOS 11

### ISSUE THREAD

**Issue by MatrixSenpai** [mamaral/Neon#60]
I really like this library and its simplicity in layouts. Is there any plans to update?

**Comment by mamaral** [comment]
Haven't had any personal cycles to look into this. What changes would need to be made to support iOS 11?

**Comment by MatrixSenpai** [comment]
![ex](https://user-images.githubusercontent.com/2157565/32125981-765b8e5a-bb3c-11e7-9c55-c6e192ccebcc.png)
Interestingly enough, seems like it's not needed. Everything appears to be fine...assuming no one else has any issues
