### ISSUE TITLE
Autolayout question

### ISSUE THREAD

**Issue by jyounus** [mamaral/Neon#7]
Hey there,

I was wondering what this is using under the hood? Are we able to "mix and match" auto layout constraints via Storyboard and Neon for some other views?

Thanks and great job with this!

**Comment by zdenektopic** [comment]
it is simply calculating the frames ;)

at least i believe so from what i saw in the code

**Comment by jyounus** [comment]
Yeah, just seen it myself as well. I was wondering how this would work with the split screen iPad feature?

**Comment by mamaral** [comment]
I'm still looking into making this compatible with the size class stuff - AFAIK that's the way to make it work with split screen. There's nothing prevent the views from properly resizing if the screen size changes, that's the whole point of this Neon, but I think I have to implement a few methods to tell the OS that its supported.

**Comment by zdenektopic** [comment]
Well dont you have to simply recalculate the frames if window size and the size class changes?

**Comment by mamaral** [comment]
Not sure, but if that's the case it'll be pretty easy. The size class documentation really sucks though, I can't find anything not related to storyboards.

**Comment by zdenektopic** [comment]
In code you work with size classes with the help of UITraitCollection. An article on that topic http://blog.flatironschool.com/working-with-size-classes-in-code-with/.

**Comment by mamaral** [comment]
Awesome - checking that out ASAP. Thanks @zdenektopic!
