### ISSUE TITLE
AsyncDisplayKit

### ISSUE THREAD

**Issue by zdenektopic** [mamaral/Neon#8]
I saw in some issue in Facebooks ASDK that someone wanted to use Neon with ASDK. They told him it would be difficult to implement but I think its as easy as

```
extension ASDisplayNode : Frameable, Anchorable, Alignable, Groupable {
    public var superFrame: CGRect {
        guard let supernode = supernode else {
            return CGRectZero
        }

        return supernode.frame
    }
}
```

Isn't it?

**Comment by wieseljonas** [comment]
So Neon doesn't use autolayout?

**Comment by mamaral** [comment]
@wieseljonas No, it doesn't. Feel free to dig into the code, it's fairly simple.

**Comment by wieseljonas** [comment]
Boy @mamaral  I'm in love with Neon :+1:

**Comment by mamaral** [comment]
Thanks @wieseljonas!! :) Hopefully will be making improvements and updates soon!
